- name: Install RedHat dependencies
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "{{ redhat_packages }}"
  when: ansible_os_family == 'RedHat'

- name: Install Debian dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  loop:
    - "{{ debian_packages }}"
  when: ansible_os_family == "Debian"

- name: Download server
  get_url:
    url: http://dedcon.simamo.de/bin/dedcon-i686-pc-linux-gnu-1.6.0_svn1038.tar.bz2
    dest: /tmp/dedcon.tar.bz2
    mode: '0440'

- name: Extract archive
  ansible.builtin.unarchive:
    src: /tmp/dedcon.tar.bz2
    dest: /srv
    remote_src: true
    unsafe_writes: true

- name: Create symbolic link
  file:
    src: "/srv/dedcon-i686-pc-linux-gnu-1.6.0_svn1038"
    dest: "/srv/dedcon"
    state: link

- name: Create user
  user:
    name: dedcon
    groups:
    - daemon
    state: present
    shell: /sbin/nologin
    system: false
    createhome: true
    home: /srv/dedcon

- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  loop:
      - /srv/dedcon/dir