---
- name: Deploying on Debian-based
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Deploying on RedHat-based
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
