---
- name: Install dependencies for Debian
  package:
    name:
      - "{{ item }}"
    state: present
  loop:
    - libc6:i386
    - libncurses5:i386
    - libstdc++6:i386
    - zlib1g:i386
  when: ansible_os_family == 'Debian'
  tags:
    - system

- name: Install dependencies for RedHat
  package:
    name:
      - "{{ item }}"
    state: present
  loop:
    - glibc.i686
    - ncurses-libs.i686
    - libstdc++.i686
    - zlib.i686
  when: ansible_os_family == 'RedHat'
  tags:
    - system

- name: Download server tarball
  get_url:
    url: >
           http://dedcon.simamo.de/bin/dedcon-i686-pc-linux-gnu-1.6.0_svn1038.tar.bz2
    dest: /tmp/dedcon.tar.bz2
    mode: '0440'

- name: Extract archive on Debian
  unarchive:
    src: /tmp/dedcon.tar.bz2
    dest: /srv
    remote_src: yes
  when: ansible_os_family == 'Debian'

- name: Extract archive on RedHat
  shell: tar -jxf /tmp/dedcon.tar.bz2 -C /srv
  args:
    executable: /bin/bash
  when: ansible_os_family == 'RedHat'

- name: Create symbolic link
  file:
    src: "/srv/dedcon-i686-pc-linux-gnu-1.6.0_svn1038"
    dest: "/srv/dedcon"
    state: link

- name: Create a login user
  user:
    name: dedcon
    groups:
      - daemon
    state: present
    shell: /sbin/nologin
    system: yes
    create_home: yes
    home: /srv/dedcon

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  loop:
    - /srv/dedcon/dir
