dependency:
  name: galaxy
role_name_check: 1
driver:
  name: docker
#lint:
#  name: yamllint
#  options:
#    config-file: molecule/default/yamllint.yml
platforms:
  - name: ansible-role-test-DEBIAN
    #image: "geerlingguy/docker-debian9-ansible"
    image: "geerlingguy/docker-ubuntu2004-ansible"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: ansible-role-test-RHEL
    image: "geerlingguy/docker-rockylinux8-ansible"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      exclude:
        - molecule/default/playbook.yml
      x:
        - 204  # Lines should be no longer than 160 chars
        - 403  # Package installs should not use latest
        - 502  # All tasks should be named
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
scenario:
  name: default
verifier:
  name: testinfra
#  lint:
#    name: flake8