---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
platforms:
  - name: ansible-role-test-debian
    image: "geerlingguy/docker-ubuntu2004-ansible"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true

  - name: ansible-role-test-redhat
    image: "geerlingguy/docker-centos8-ansible"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      exclude:
        - molecule/default/converge.yml
      x:
        - 204  # Lines should be no longer than 160 chars
        - 403  # Package installs should not use latest
        - 502  # All tasks should be named
scenario:
  name: default
verifier:
  name: testinfra
